'use strict';

var execFile = require('child_process').execFile;
var path = require('path');
var test = require('tap').test;

var ERRORS = [
  '',
  'react-commonjs-error.js:16:10,16: property `onClick`',
  'Property not found in',
  'react-commonjs-error.js:5:7,10: Home',
  '',
  'react-commonjs-error.js:20:22,26: property `title`',
  'Property not found in',
  'react-commonjs-error.js:5:7,10: Home',
  '',
  'react-commonjs-error.js:25:17,23: function call',
  'Function cannot be called on',
  'react-commonjs-error.js:25:17,21: string',
  '',
  'react-commonjs-error.js:30:1,19: props of React element `Home`',
  'Error:',
  'react-commonjs-error.js:30:14,15: number',
  'This type is incompatible with',
  'react-commonjs-error.js:11:12,21: string',
  '',
  'react-commonjs-error.js:32:1,19: call of method `render`',
  'Error:',
  'react-commonjs-error.js:32:17,18: number',
  'This type is incompatible with',
  '[LIB] react.js:237:14,34: React$Element',
  '',
  'react-commonjs-error.js:33:1,24: call of method `findDOMNode`',
  'Error:',
  'react-commonjs-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:13,56: union: type application of polymorphic type: class type: React$Component | HTMLElement',
  'Member 1:',
  '[LIB] react.js:233:13,42: type application of polymorphic type: class type: React$Component',
  'Error:',
  'react-commonjs-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:13,42: React$Component',
  'Member 2:',
  '[LIB] react.js:233:46,56: HTMLElement',
  'Error:',
  'react-commonjs-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:46,56: HTMLElement',
  '',
  'react-commonjs-error.js:35:22,66: call of method `renderToStaticMarkup`',
  'Error:',
  'react-commonjs-error.js:35:22,66: string',
  'This type is incompatible with',
  'react-commonjs-error.js:35:13,18: number',
  '',
  'react-es-module-error.js:16:10,16: property `onClick`',
  'Property not found in',
  'react-es-module-error.js:5:7,10: Home',
  '',
  'react-es-module-error.js:20:22,26: property `title`',
  'Property not found in',
  'react-es-module-error.js:5:7,10: Home',
  '',
  'react-es-module-error.js:25:17,23: function call',
  'Function cannot be called on',
  'react-es-module-error.js:25:17,21: string',
  '',
  'react-es-module-error.js:30:1,19: props of React element `Home`',
  'Error:',
  'react-es-module-error.js:30:14,15: number',
  'This type is incompatible with',
  'react-es-module-error.js:11:12,21: string',
  '',
  'react-es-module-error.js:32:1,19: call of method `render`',
  'Error:',
  'react-es-module-error.js:32:17,18: number',
  'This type is incompatible with',
  '[LIB] react.js:237:14,34: React$Element',
  '',
  'react-es-module-error.js:33:1,24: call of method `findDOMNode`',
  'Error:',
  'react-es-module-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:13,56: union: type application of polymorphic type: class type: React$Component | HTMLElement',
  'Member 1:',
  '[LIB] react.js:233:13,42: type application of polymorphic type: class type: React$Component',
  'Error:',
  'react-es-module-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:13,42: React$Component',
  'Member 2:',
  '[LIB] react.js:233:46,56: HTMLElement',
  'Error:',
  'react-es-module-error.js:33:22,23: number',
  'This type is incompatible with',
  '[LIB] react.js:233:46,56: HTMLElement',
  '',
  'react-es-module-error.js:35:22,66: call of method `renderToStaticMarkup`',
  'Error:',
  'react-es-module-error.js:35:22,66: string',
  'This type is incompatible with',
  'react-es-module-error.js:35:13,18: number',
  '',
  'Found 14 errors',
  '',
].join('\n');

test('react-for-atom flow react', function (t) {
  t.plan(1);
  // flow check --old-output-format --strip-root
  var flow = require('flow-bin');
  execFile(flow, ['check', '--old-output-format', '--strip-root'], {
    cwd: path.join(__dirname, 'flow-react')
  }, function (err, stdout) {
    t.equal(stdout, ERRORS);
  });
});
